version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - WEBAPP_URL=${WEBAPP_URL}
    restart: unless-stopped
    depends_on:
      - webapp
    networks:
      - tg-network

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "${WEBAPP_PORT:-8000}:8000"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_TOKEN}
    restart: unless-stopped
    networks:
      - tg-network

networks:
  tg-network:
    driver: bridge